### ISSUE TITLE
Change log for version 0.7

### ISSUE THREAD

**Issue by KirstieJane** [taynaud/python-louvain#10]
Wooo! A new version of  `community`! Thank you! 🙌 ✨ 

Looking through I can see a `resolution` parameter in the [best_partition](https://github.com/taynaud/python-louvain/blob/master/community/community_louvain.py#L133) command that I don't remember being in the previous version? Am I right or do I have poor memory on that front?

I think that this equivalent to the `gamma` option that's used as part of the Brain Connectivity Toolbox [community_louvain.m](https://sites.google.com/site/bctnet/measures/list#TOC-Clustering-and-Community-Structure) code.

More generally, is there a changelog that I can take a look through to see what has updated?

Thank you again for this really helpful module!!

**Comment by taynaud** [comment]
Hello,

Thanks for your comments :)

There is no changelog yet, I may start to write one for nex versionst. There are not a lot of new stuffs in the new version, mostly internals changes. Basically:

* Move to github, travis and readthedocs
* Fix some small bugs (typos, issue in the community command line interface which was not installed anymore)
* Add a resolution parameter

This resolution is described in  "Laplacian Dynamics and Multiscale Modular Structure in Networks",
        R. Lambiotte, J.-C. Delvenne, M. Barahona

It allows to get more communities by setting a resolution < 1 and less communities with resolution > 1. It looks like `gamma` but I do not understand matlab enough to assure you it is the same.

The next version will allow to randomize some parts of the algorithm to allow to get different partitions on different run.

Best,

**Comment by KirstieJane** [comment]
Fantastic! Thank you!

My colleagues use matlab and I'm useless with it so this new update lets me do their analyses (with different resolutions) in python. Yaaaaay!

Thanks again - I'm closing this as you've answered my question :)
