### ISSUE TITLE
How can I get the first status of the communities?

### ISSUE THREAD

**Issue by ricklovelisa** [taynaud/python-louvain#11]
How can I get the first status of the communities?
I can just get the final communities, but I want get every status of the communities, How can I get them? or I have to modify the method?

**Comment by taynaud** [comment]
Hello,

What do you mean by status of the communities ?

If you want all the communities hierarchy, you can use `generate_dendrogram` and `partition_at_level`

Best,

**Comment by ricklovelisa** [comment]
Thank you very much！
