### ISSUE TITLE
How to cite

### ISSUE THREAD

**Issue by jcatumba** [taynaud/python-louvain#16]
Hi. I want to add a citation to this software. What should I put? Thanks.

**Comment by taynaud** [comment]
Hello,

I do not expect specific citation for using this implementation. 


You'll need to cite the algorithm implemented:

```
Fast unfolding of communities in large networks,
Vincent D Blondel, Jean-Loup Guillaume, Renaud Lambiotte, Etienne Lefebvre,
Journal of Statistical Mechanics: Theory and Experiment 2008 (10), P10008 (12pp)
doi: 10.1088/1742-5468/2008/10/P10008. ArXiv: http://arxiv.org/abs/0803.0476
```

cf https://perso.uclouvain.be/vincent.blondel/research/louvain.html

Of course, a link to the github and/or a mail to me describing your usage is always appreciated :)

Best,
