### ISSUE TITLE
Dendrogram Question

### ISSUE THREAD

**Issue by leomaurodesenv** [taynaud/python-louvain#22]
Hello,
I want to know it is possible to explore all dendrogram levels.
Like one to one node in each level, also plot this.

I'm trying to understanding `generate_dendrogram()`, but have some difficulties.
What means each `partition_at_level()` of the generated dendrogram?

Thanks for all!

**Comment by taynaud** [comment]
Hello,

`generate_dendrogram` will generate a tree. It is represented as a list of dictionary. 
The first one will have node as key and first partitioning as value. The second one will have first partitioning as key, second partitioning as value. It continues until you cannot optimize more the modularity.

`partition_at_level` is a helper function which will transform a dendogram to a partition, i.e a dictionary with graph nodes as key and community as values, for a given level in the dedogram.

**Comment by leomaurodesenv** [comment]
Thanks a lot @taynaud . Now I understood.

**Comment by dsaffo** [comment]
Is there an example of how to plot a dendrogram from this format? I am still a bit confused

**Comment by leomaurodesenv** [comment]
Hello @dsaffo,
Before I'm thinking in a complete dendrogram, like [Girven-Newman](https://en.wikipedia.org/wiki/Girvan%E2%80%93Newman_algorithm). However, the Louvain Modularity converges in a different way. Thus, your dendrogram is more compact (based on community aggregation step). See the paper [Fast unfolding of communities in large networks](http://iopscience.iop.org/article/10.1088/1742-5468/2008/10/P10008/meta).

This is an [example](https://python-louvain.readthedocs.io/en/latest/api.html#community.generate_dendrogram):
```python
G=nx.erdos_renyi_graph(100, 0.01)
dendo = generate_dendrogram(G)
for level in range(len(dendo) - 1) :
    print("partition at level", level, "is", partition_at_level(dendo, level))
```

Note, the level starts from zero, and the higher the level is, the bigger are the communities. Of course, depending on your graph.
