### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by dharif23** [taynaud/python-louvain#24]
I am trying to compile a simple community detection on karate club data with both C++ and python.
Here is what I did:

Downloaded - [This C++ version of Louvain from Source Forge](http://sourceforge.net/projects/louvain/files/louvain-generic.tar.gz/download
)
Also downloaded - karate club data from [here](https://sourceforge.net/p/louvain/code/ci/default/tree/sample_networks/karate.txt) 
run command - `make all`
once done, `./convert -i karate_club.txt -o karate_club.bin`

I cloned the repo of python-Louvain and run
`sudo python setup.py install`

I also run `sudo python setup.py test`

Everything is okay till this point

When I run
`community karate_club.bin`
It shows following -
```python
Traceback (most recent call last):
  File "/usr/local/bin/community", line 26, in <module>
    main()
  File "/usr/local/bin/community", line 14, in main
    print(str(modularity(partition, graph_file)), file=sys.stderr)
  File "/usr/local/lib/python2.7/dist-packages/community/community_louvain.py", line 116, in modularity
    raise ValueError("A graph without link has an undefined modularity")
ValueError: A graph without link has an undefined modularity
```

**Comment by taynaud** [comment]
Hello,

I think the format used by the CPP version has changed a little, thus the community executable fails to read it properly. You may try with an older version of the cpp file, or use it as a library and read the graph using networkx.

I will add some details on the documentation about how to do that, I think that handling the CPP version format has not a lot of value for the moment (correct me if it is important for you).

Best

**Comment by dharif23** [comment]
Thanks for the clarification. I have used **python** version of the algorithm entirely to avoid this situation. I really appreciate that you taking the time to clarify this and hopefully after adding a little bit of documentation about it will help others not avoid it in the first place.
