### ISSUE TITLE
Usage with external datasets

### ISSUE THREAD

**Issue by w4bo** [taynaud/python-louvain#26]
Hi,

It should be useful to add working (and runnable) examples with external datasets (e.g., csv), such that it is easier to understand how things works and how results should be interpreted

**Comment by dharif23** [comment]
This might help you - take a look

[https://github.com/dharif23/notebooks/blob/master/louvain.ipynb](https://github.com/dharif23/notebooks/blob/master/louvain.ipynb)

**Comment by taynaud** [comment]
Example code from the documentation is now on the readme, feel free to reopen if you need more examples.

Best,
