### ISSUE TITLE
community.best_partition on completely isolated nodes graph 

### ISSUE THREAD

**Issue by deter3** [taynaud/python-louvain#31]
I am processing lots of hashtags networkx graphs , trying to find the community . The procedure needs to remove lots of hashtags . Some time the detected communities has tag name as cluster label .  I found out if the graph has 100% isolated nodes as below image  , then cluster label will be nodes name . 
![image on 2018-10-30 12 42 35 pm](https://user-images.githubusercontent.com/11637246/47696634-a04aa980-dc42-11e8-82cd-3b243f66e45c.jpg)

If there is any connected nodes , then the detected communities has normal cluster label as 0,1,2,3 etc .  see image below . 
![image on 2018-10-30 12 47 32 pm](https://user-images.githubusercontent.com/11637246/47696673-cb34fd80-dc42-11e8-919d-a32d0f3ee735.jpg)

**Comment by taynaud** [comment]
Hello,

You're right, there is a special case when there are no links to return a partition node <-> itself. It would be a bit cleaner to always provide clusters in [0... n_cluster].

This will be fixed in next release.

Thanks
