### ISSUE TITLE
fileformat

### ISSUE THREAD

**Issue by cosai** [taynaud/python-louvain#33]
Hi,

Can you give an example file format in the description? You stated something about C implementation? Where is that implementation? How can I learn the file format? At least can you post some links?

regards

cosai

**Comment by taynaud** [comment]
Hi,

The file format is the one used by the original implementation at https://sites.google.com/site/findcommunities/

I advised not to use this format (it was first to compare results with original implementation) but use this module as a library and load the network yourself with networkx helpers.

You'll find an exemple at https://python-louvain.readthedocs.io/en/latest/ using an erdos_renyi graph, just change:

```

#better with karate_graph() as defined in networkx example.
#erdos renyi don't have true community structure
G = nx.erdos_renyi_graph(30, 0.05)
```

With relevant code to load your graph with networkx.

I will improve documentation about that,

Thanks,

Best,
