### ISSUE TITLE
Random state does not work with graph with mixed node types

### ISSUE THREAD

**Issue by taynaud** [taynaud/python-louvain#35]
Hey, so it turns out that this change makes the package not work for some graphs, because the list returned by numpy RandomState.permutation sometimes does not contain the same items that were in the list passed to it.  The particular case that I ran into was that my networkx graph has some nodes whose labels are strings and others whose labels are integers, but the RandomState.permutation was turning all of them into strings, which then caused a KeyError.  It seems like replacing `random_state.permutation(list(graph.nodes()))` with `random_state.permutation(np.array(graph.nodes(), dtype=object))` might solve this problem.

_Originally posted by @akenney in https://github.com/taynaud/python-louvain/commit/ed63d74f152ce9ff7febe1459319d719a7f32f0c#commitcomment-31809462_

**Comment by pavlin-policar** [comment]
It would be best if @akenney opens a PR with the fix since he can reproduce the issue and will best know when it's fixed.
