### ISSUE TITLE
Louvian method takes longer than the Clauset_Newman implemented in netrowkX.algorithm

### ISSUE THREAD

**Issue by afshinfard** [taynaud/python-louvain#40]
Hi,
I am in need of a community detection algorithm for networkX graphs. Having looked into the literature, I believe that the louvian method is theoretically faster, and more suitable for my case than the earlier modularity-based approach proposed by Clauset and Newman.
In search of implementations, I found that you've done that. Thanks for doing so. As I found, the networkX.algorithm has an implementation of the Clauset and Newman algorithm, and surprisingly it performs faster than this version. I am working on around 600K graphs of len: 20<len<1000 and it takes around 5 mins with Clauset_Newman and around 6 hours with louvian.
I still believe that in case of accuracy this algorithm is more suitable for me and wondering if am missing a point or something...

**Comment by taynaud** [comment]
Hello,

Louvain method is in general way faster... for large graphs with communities. On small graphs with a not clear community structure, I would not be surprised that the initialization + the time to converge would be costly.

Can you provide some samples of your graph for further analysis ?

**Comment by afshinfard** [comment]
Thanks for your response,
I will upload some examples as soon as I get access to my system. In the problem I am working on, we have a very large graph. We iterate over vertices, and for each one we extract the vertex-induced subgraph of the that vertex (excluding itself). Then we run detect communities on that subgraph. The reason we do so is that our vertices are convoluted (a mix of sub-vertices) and we want to deconvolute them. I explained all these to ask if uploading the original graph suffices, or you prefer a bunch of subgraphs extracted into a file?

**Comment by taynaud** [comment]
I would prefer directly the graphs on which you apply the algorithms. If I understand correctly it would be subgraphs.

Keep in mind that ego-networks centered on a vertice have different structures than "standard" graphs and maybe the Clauset_Newman implementation of networkX have better behavior on such graph.

You may also need the C++ version of the algorithm which is a lot faster.
