### ISSUE TITLE
is_isomorphic: error

### ISSUE THREAD

**Issue by andreacortis** [taynaud/python-louvain#42]
Hello, I am trying to figure out if this is a versioning problem or simply a bug.
Thanks

Andrea

```
(py36) Gundam:~ andreacortis$ ipython
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import networkx 
   ...: import community 
   ...: print(f'networkx.__version__ = {networkx.__version__}')
   ...: print(f'community.__version__ = {community.__version__}')
   ...: n = 5
   ...: g = networkx.complete_graph(2*n)
   ...: part = dict([])
   ...: for node in g.nodes() :
   ...:     part[node] = node % 2
   ...: ind = community.induced_graph(part, g)
   ...: goal = networkx.Graph()
   ...: goal.add_weighted_edges_from([(0,1,n*n),(0,0,n*(n-1)/2), (1, 1, n*(n-1)/2)])  # NOQA
   ...: networkx.is_isomorphic(int, goal)
   ...: 
networkx.__version__ = 2.2
community.__version__ = 0.13
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-60e856d1a473> in <module>()
     11 goal = networkx.Graph()
     12 goal.add_weighted_edges_from([(0,1,n*n),(0,0,n*(n-1)/2), (1, 1, n*(n-1)/2)])  # NOQA
---> 13 networkx.is_isomorphic(int, goal)

~/Envs/py36/lib/python3.6/site-packages/networkx/algorithms/isomorphism/isomorph.py in is_isomorphic(G1, G2, node_match, edge_match)
    228        http://amalfi.dis.unina.it/graph/db/papers/vf-algorithm.pdf
    229     """
--> 230     if G1.is_directed() and G2.is_directed():
    231         GM = nx.algorithms.isomorphism.DiGraphMatcher
    232     elif (not G1.is_directed()) and (not G2.is_directed()):

AttributeError: type object 'int' has no attribute 'is_directed'

```

**Comment by dharif23** [comment]
By the looks of it, it seems a `networkx` error.
Please look at the documentation of `is_isomorphic` [here](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.isomorphism.is_isomorphic.html#networkx.algorithms.isomorphism.is_isomorphic) 
Feel free to check this out!

**Comment by andreacortis** [comment]
ah, now I see. It is a typo in your documentation. I . mindlessly copy&paste the line 

`networkx.is_isomorphic(int, goal)`

but that should read instead:

`networkx.is_isomorphic(ind, goal)`

If you fix the typo in the documentation we can close it. Thanks!

**Comment by dharif23** [comment]
Hi, @andreacortis I think you should create a PR (pull request) if you want to fix the documentation. I am neither the maintainer not involved in the repo. I think you should fix the issue and create a pull request and see what the admin says about it.

**Comment by taynaud** [comment]
Thanks for the fix !

**Comment by llinfeng** [comment]
@taynaud The example code on [this page](https://python-louvain.readthedocs.io/en/latest/api.html#community.induced_graph) still have `int` in place. You can search for "is_isomorphic" to find the line.

**Comment by taynaud** [comment]
It should be fix, thanks
