### ISSUE TITLE
modularity is 0

### ISSUE THREAD

**Issue by MogicianEik** [taynaud/python-louvain#45]
Hi Developers, I defined a completely connected undirected graph. Each edge has its unique weight. When I partitioned the graph, the result showed no community was found. Is it normal? What factors I need to consider if I want to find communities inside my graph?

**Comment by taynaud** [comment]
Hello,

A modularity of 0 may happen on very strange graphs, but it looks more like a bug. My main hypothesis would be that the graph has no edges.

Can you provide a small example of a graph on which you have no communities ? What is your result: every node in the same community or in its own community ?
