### ISSUE TITLE
reading digraph with weights from file

### ISSUE THREAD

**Issue by rkatriel-mdsol** [taynaud/python-louvain#49]
Hi,

I'm getting the following error from community.best_partition when passing it a weighted graph that is read from a file:

TypeError: unsupported operand type(s) for +: 'int' and 'str'

The code is as follows

import community
import networkx.drawing.nx_pydot as pd
import networkx as nx
G = nx.Graph(pd.read_dot('data.gv'))
partition = community.best_partition(G)

Here is what an edge looks like in the input file (data.gv)

	"A" -> "B" [weight=10.0];

Surprisingly, I don't get this error when I set the weight in the program as follows

G = nx.Graph()
G.add_edge('A', 'B', weight=10.0)

This appears to be a subtle bug in the louvain package (it doesn't properly handle the weights when imported from a dot file).

Thanks,
Ron

**Comment by taynaud** [comment]
Can you provide a full stack trace and maybe an example dot file ?

From what I understand, G after loading contains weight of type str and weights of type int. Maybe they are all strings except some where it is not set and thus become 1 by default.

In this case, I would prefer to let the user clean the input G (maybe we could just add a better error reporting) than implementing some guesses of what the algorithm should do of a "str" weight.

**Comment by SakibMostafa** [comment]
> Can you provide a full stack trace and maybe an example dot file ?
> 
> From what I understand, G after loading contains weight of type str and weights of type int. Maybe they are all strings except some where it is not set and thus become 1 by default.
> 
> In this case, I would prefer to let the user clean the input G (maybe we could just add a better error reporting) than implementing some guesses of what the algorithm should do of a "str" weight.

Hi,
I am getting the same error after reading the graph from a ".csv" file. What can be a possible solution?

**Comment by SakibMostafa** [comment]
> Can you provide a full stack trace and maybe an example dot file ?
> 
> From what I understand, G after loading contains weight of type str and weights of type int. Maybe they are all strings except some where it is not set and thus become 1 by default.
> 
> In this case, I would prefer to let the user clean the input G (maybe we could just add a better error reporting) than implementing some guesses of what the algorithm should do of a "str" weight.

I think the problem arises when you read a file using the read function. It will be read as a string. So the weights are also read as string. The workaround would be to update the modularity_max.py function. In particular the variable m. You can update it as
 m = sum([float(d.get('weight', 1)) for u, v, d in G.edges(data=True)])
So the degree will be read as a float value rather than the actual value. Doing so you will get few more errors. You will need to update all the cases where the weight is read and simply use type casting.

**Comment by JulianSchmidtke** [comment]
Example DOT File:
```
digraph G {
  "A" -> "C" [weight=5];
  "B" -> "C" [weight=8];
}
```

Stack Trace (i could not install python_louvain and copied the files)

```
Exception has occurred: TypeError
unsupported operand type(s) for +: 'int' and 'str'
  File "C:\Repositories\pycommunities\community\community_status.py", line 46, in init
    self.total_weight = graph.size(weight=weight)
  File "C:\Repositories\pycommunities\community\community_louvain.py", line 345, in generate_dendrogram
    status.init(current_graph, weight, part_init)
  File "C:\Repositories\pycommunities\community\community_louvain.py", line 244, in best_partition
    dendo = generate_dendrogram(graph,
  File "C:\Repositories\pycommunities\community.py", line 98, in louvain
    comm = commnity.best_partition(g)
  File "C:\Repositories\pycommunities\community.py", line 26, in main
    louvain(G)
  File "C:\Repositories\pycommunities\community.py", line 140, in <module>
    main()
```

**Comment by taynaud** [comment]
The issue seems to be in graph loading and not in the algorithm itself. I would prefer to let the user clean the input G than adding a specific fix for that.

Thanks for the report,

**Comment by rxk2rxk** [comment]
Just got notification about this. Been a year since I opened the issue so not as helpful but will keep the workaround in mind for future use. Thanks all!

**Comment by AoeshaAlsobhe** [comment]
Im getting same error
