### ISSUE TITLE
miscalculation the local modularity gain

### ISSUE THREAD

**Issue by datazhen** [taynaud/python-louvain#51]
Hi,
I  derived a formula which is the gain in modularity  when removing a node i from its community :
![WechatIMG386](https://user-images.githubusercontent.com/20197140/60706323-cf38be00-9f3b-11e9-847a-a95f62dadcd3.jpeg)

 but it looks a little different followed in `community_louvain.__one_level()`  module:
> `remove_cost = - resolution * neigh_communities.get(com_node,0) + \
>                 (status.degrees.get(com_node, 0.) - status.gdegrees.get(node, 0.)) * degc_totw
> `

should we change `status.gdegrees.get(node, 0.)` to `status.gdegrees.get(node, 0.)/2`?

**Comment by taynaud** [comment]
I think that this /2 is already applied in degc_totw ?
