### ISSUE TITLE
Adding a CITATION file.

### ISSUE THREAD

**Issue by Nikoleta-v3** [taynaud/python-louvain#53]
I am currently using your library for one of my research projects. I was wondering if you would be interested in creating a citation file so the library can be cited.

Here is a very good blog post on why/who citing your software is good practice: https://www.software.ac.uk/blog/2016-10-06-encouraging-citation-software-introducing-citation-files

Let me know if you would like me to open a pull request 👍

**Comment by taynaud** [comment]
Hello,

You do not need to cite this for your research projects, but I am always open to pull request !

**Comment by Nikoleta-v3** [comment]
Thank you for your reply @taynaud. 
 
No I would really like to cite the package actually. It has helped me with my work and I believe the you and the rest of the contributors should get credit for it. 

I will open a `PR` 😄
