### ISSUE TITLE
Mean weight for induced_graph

### ISSUE THREAD

**Issue by Kawue** [taynaud/python-louvain#54]
Is there an easy way to compute the mean weight for the induced graph instead of the sum?
Currently I used a modified version, which adds a counter value in the edge attribute dict to calculate the mean later when I need it.

**Comment by taynaud** [comment]
Hello,

Can you describe more what you are trying to achieve ? The Louvain algorithms alternate several phases of optimization, and between them reduce the graph to the "induced graph". This last is the graph between communities and one property of it is that assigning each node of this induced graph to its own community have the same modularity than the partition found on the graph before. If you take average, you would change this property and maybe loose the algorithm convergence.

Best

**Comment by Kawue** [comment]
I need the mean for a visualization tool. I was not aware of this property and this is good to know. In my visualization the sum would interfere with some of my forces. By adding a counter I can use the mean without conflicting with your algorithm. Now that I know of this property I think replacing it after the algorithm converged and using it only for visualization purposes is a good way to go.

Thank you.
