### ISSUE TITLE
Does this support weighted graph?

### ISSUE THREAD

**Issue by neverUseThisName** [taynaud/python-louvain#56]
The demo in readme work in an unweighted graph. Does this support weighted graphs?

**Comment by seralouk** [comment]
Yes. https://github.com/taynaud/python-louvain/blob/master/community/community_louvain.py#L163

**Comment by taynaud** [comment]
The implementation supports weighted graph. The weights should be an attribute of the edges. The higher the weight, the stronger the connection is. By default, the attribute read is `weight`.
