### ISSUE TITLE
community_louvain and pylouvain algorithms gives different results of community

### ISSUE THREAD

**Issue by himanshucodz55** [taynaud/python-louvain#66]
Hi,
I am working on a community detection using pylouvain and community_louvain. but i have one issue regarding that both give different results of community.

**Comment by himanshucodz55** [comment]
![Screenshot (95)](https://user-images.githubusercontent.com/49410142/84494177-a8941300-acc6-11ea-904f-f34870bbf316.png)

you can that leftmost part shows a graph using community_louvain and rightmost part shows the results of pylouvain and it gives final communities...

**Comment by taynaud** [comment]
Louvain algorithm is not totally deterministic. It depends on an ordering of the node which has no clear definition on a graph. During a pass, it does an iteration on each nodes of the graph and there is different order of iteration. Thus you may easily find different results, even for the same graph just by relabeling the nodes. By experience you should get very similar modularities at the end.
