### ISSUE TITLE
Get more granular levels in the dedrogram

### ISSUE THREAD

**Issue by stelmath** [taynaud/python-louvain#67]
Hello @taynaud and thanks for the great package. I have this scenario: I am working on a network where nodes are representing words/terms (example: "blue", "light blue", "color", "tool", "hammer", "nail", etc.) and two nodes are connected with an edge if the cosine similarity of the embeddings of those words is greater than a threshold. I have a pretty big network of such words formed using `networkx`. 

When I used louvain I only got 2 communities of words, which does not really represent the true communities. I would expect a community with words related to cars, food, tools, etc. I then saw the functions like `partition_at_level()` and `generate_dendrogram()`. These were somewhat helpful, but I would like to get even more levels in the dendrogram so I can reveal sub-communities (example: baking food and seafood words on level 0 and then these merge into food words on level 1 etc.) 

In this example I only get 2 levels, no matter what `resolution `value I use:

```
import networkx as nx
import community as community_louvain
import matplotlib.cm as cm
import matplotlib.pyplot as plt

dendo = community_louvain.generate_dendrogram(nx.karate_club_graph())
for level in range(len(dendo)):
            pos = nx.kamada_kawai_layout(nx.karate_club_graph())
            # color the nodes according to their partition
            number_of_communities = max(community_louvain.partition_at_level(dendo, level).values()) + 1
            print(f'For level: {level} of the dedrogram we have {number_of_communities} communities')

            cmap = cm.get_cmap('Paired_r', number_of_communities + 1)
            nx.draw_networkx_nodes(nx.karate_club_graph(), pos, community_louvain.partition_at_level(dendo, level).keys(), node_size=90,
                                   cmap=cmap, node_color=list(community_louvain.partition_at_level(dendo, level).values()))
            nx.draw_networkx_edges(nx.karate_club_graph(), pos, alpha=0.2)
            nx.draw_networkx_labels(nx.karate_club_graph(), pos)
            plt.show()
            plt.clf()
```

So, is it possible to get more levels in the dedrogram with louvain? Should I explore another community detection algorithm maybe? Thanks!

**Comment by ldorigo** [comment]
I would also like to know. From what I understand of the algorithm, it starts from communities of one node and builds progressively larger communities to optimize modularity - but most of my dendrograms only have one or two levels? Not sure what's going on.

**Comment by stelmath** [comment]
I ended up using the igraph implementation and recursively applying the Louvain until the sub-communities can't be further be broken down @ldorigo

**Comment by taynaud** [comment]
Dendogram depth is not controlable. The algorithm is in several pass, and each level corresponds to one pass.

During a pass, the algorithm move nodes to optimize modularity locally and a pass ends when you cannot increase modularity by changing one node of community. Then the algorithm build a graph between these communities (they also become a node in the dendogram) and do a pass on this new graph. It ends when you get not enough modularity increase.

Computing recursively best communities inside a community is indeed a good way to get deeper and more sound trees
