### ISSUE TITLE
No community detection (every node its own community) a bug?

### ISSUE THREAD

**Issue by amjass12** [taynaud/python-louvain#68]
Hi all, I am having a very peculiar issue when generating two graphs using identical code:

I have created two networkX graphs based on Pearson correlation of data that I have. The first set of data has the following dimensions:
```

count1=(20501,498)
count2=(20501, 31)
```
the data are both subset to contain 1800 features of interest from the 20501, so shape becomes:
```

countsub1=(1800,498)
countsub2=(1800,31)
```
again, those 1800 are exactly the same in both samples.

I then carry out the following code on BOTH sets individually:
```

corrsub1=pd.DataFrame.corr(countsub1, method="pearson")
corrsub2=pd.DataFrame.corr(countsub2, method="pearson")

networkGraph1=nx.Graph(corrsub1).to_undirected()
networkGraph2=nx.Graph(corrsub2).to_undirected()


#remove edges below Pearson correlation threshold

edge_weights = nx.get_edge_attributes(networkGraph1,'weight')
networkGraph1.remove_edges_from((e for e, w in edge_weights.items() if w <0.8))
#remove non-connected vertices
for component in list(nx.connected_components(networkGraph1)):
    if len(component)<2:
        for node in component:
            networkGraph1.remove_node(node)
.... and the same for the other...

community detection
comm1 = community.best_partition(networkGraph1)
comm2 = community.best_partition(networkGraph2)
```

all steps are carried out identically... in BOTH correlation tables, there are significant correlation values >0.8 etc. AND there are communities I know exist in BOTH correlation tables, as I have observed these in iGraph. In fact there are at least 20 nodes with edges that connect each other (and have a pearson corr >0.8).

The issue is:the network generated with 498 sample counts, generates without issue and produced ~50 communities...

The network with 31 samples (network2) does not render a single node when calling nx.draw_networkx. When I run:

pos=nx.fruchterman_reingold_layout(networkGraph2, seed=50)
it shows:

'feature1': array([nan, nan]),... from first to last feature

when I run pos.. for networkGraph1, coordinates show fine as follows:

'feature1': array([-0.0988057 , -0.48840776]),

Additionally, when I run the community.best_partition:

**NetworkGraph1= ~50 communities networkGraph2= 1800 communities (number of features)**

I know for sure this isn't correct, however the code and pipeline are identical, and I'm unsure as to why this is happening. Any input would be really useful.

It seems there is something wrong with the network creation, however some insight in to why it does find communities when the code is identical would be really helpful, 

many thanks!

**Comment by taynaud** [comment]
Hello,

I think your issue is more related to graph construction than community detection. Can you show some nodes and edges with values of features for each graph ?

Best,

**Comment by amjass12** [comment]
Hi @taynaud ,

Thank you for your response and sorry for the delay in replying. I managed to fix this by simply changing the I put approach. Instead of a correlation matrix, I now stack the matrix in to a pandas dataframe containing, columns, source, target and edge_weight. 

Can I ask a follow up question about `best_partition`: edge weights required internally for community detection? What does default of `weights = 'weights' `mean? Community detection successfully finds communities which make sense to me if I use default parameters - `community.best_partition(graph)`

However if I community.best_partition(graph, weight s='edge_weight'/or whatever the column for edge weights is called in the pandas dataframe, I get a bad node error... Please could you clarify the source of this error and what the weights argument really means? 

Is it truly required for community detection? 
Thank you!

**Comment by taynaud** [comment]
Louvain algorithm can handle weighted graph. The higher the weight of a link, the stronger the connection is. In most of networkx algorithm, weight is a standard meta data on edges or nodes and you specify the name of the metadata representing the weight this way. Is is basically a way to name the weight you want to use. If this is not set, the library should default to weight=1
