### ISSUE TITLE
inconsistent modularity with python-louvain and consistent modularity with igraph "community_multilevel"

### ISSUE THREAD

**Issue by student2k21** [taynaud/python-louvain#76]
I have a directed weighted graph with 26 nodes and 41 edges (I converted directed to undirected in both cases). Highest weight is 721, and the lowest weight is 0.
After running the code mentioned in #62 with the following code with igraph louvain
```
newGraph = nx.DiGraph.to_undirected(G)  
graph = igraph.Graph.from_networkx(newGraph)  
louvain_partition = graph.community_multilevel(weights=graph.es['weight'], return_levels=False)  
modularity1 = graph.modularity(louvain_partition, weights=graph.es['weight'])  
print("The modularity Q based on igraph is {}".format(modularity1))
```

and with python-louvain
```
louvain_partition = community.best_partition(newGraph, weight='weight')  
modularity2 = community.modularity(louvain_partition, newGraph, weight='weight')  
print("The modularity Q based on networkx is {}".format(modularity2))
```

**1st run:**
The modularity Q based on igraph is 0.4040923069638124
The modularity Q based on networkx is 0.4040923069638123

**2nd run**
The modularity Q based on igraph is 0.4040923069638124
The modularity Q based on networkx is 0.3905853102404014

**3rd run**
The modularity Q based on igraph is 0.4040923069638124
The modularity Q based on networkx is 0.4040923069638123

**4th run:**
The modularity Q based on igraph is 0.4040923069638124
The modularity Q based on networkx is 0.4040923069638123

**5th run**
The modularity Q based on igraph is 0.4040923069638124
The modularity Q based on networkx is 0.4040211478582875

I have a research thesis which utilizes python-louvain for finding communities but due to this I am not sure whether to use python-louvain as it is quite easy to use with networkx and visualize

**Comment by taynaud** [comment]
Louvain algorithm is not deterministic and relies on an ordering of the nodes during an optimization pass to move each node to the neighboring community which maximize modularity. Thus you may get different results just by relabelling each nodes for instance (or by using the randomize parameter). In general you get very similar modularity.

It looks like you are in this case.
