### ISSUE TITLE
Tracing communities produced

### ISSUE THREAD

**Issue by gebaltso** [taynaud/python-louvain#77]
Hello! Is there any new suggestion on how to check if two Louvain partitions are the same after two separate runs?(Due to different labels they may have in the different runs) I mean after adding for example a new edge in the initial graph, how can I say if the adjacent to this edge nodes belong in the same communities as before the edge addition?
Thanks in advance.

**Comment by taynaud** [comment]
Hello,

Matching partition is not very straightforward. I discuss some ways in https://ieeexplore.ieee.org/abstract/document/5520221

Best.
