### ISSUE TITLE
Coefficient of `degc_totw` in modularity calculation.

### ISSUE THREAD

**Issue by wusuowei60** [taynaud/python-louvain#82]
Hi, there is my question about how the modularity is calculated during node moving.

I think the following code —

https://github.com/taynaud/python-louvain/blob/0be2657088ace315959f44e2b02030c597cf63a3/community/community_louvain.py#L483-L502

comes from such derivation —

![image](https://user-images.githubusercontent.com/57242693/114590837-d3227400-9cbb-11eb-95ba-6661e92fb8d1.png)

And to my best understanding, `degc_totw` represents

![image](https://user-images.githubusercontent.com/57242693/114592710-cef75600-9cbd-11eb-898e-ad4d35bea7b3.png)

where node c moves from community x to community y, and capital K is the degree of community and lowercase k is degree of node. (I omit resolution there).

So, where is the coefficient 2? Thank you.

**Comment by ComplexLychee** [comment]
Hi there, good spot.

I believe the discrepancy comes from the fact that there is a factor 2 in the $\delta e$ term in your derivation. The code implementation in 487-488 and 494-495 excludes the coefficient 2, which does not affect the result. 

It might be helpful to look at the equation (2) in the original Louvain paper: https://iopscience.iop.org/article/10.1088/1742-5468/2008/10/P10008/meta

**Comment by taynaud** [comment]
Thanks, indeed this coefficient does not affect the results

**Comment by wusuowei60** [comment]
Thank you Lizhi.
